on:
  push:
    - beta
    - production

name: Continuous Deployment

jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Determine environment
        id: determine_environment
        run: echo "::set-output name=environment::${GITHUB_REF#refs/heads/}"
      - name: Decrypt ${{ steps.determine_environment.outputs.environment }} secrets
        uses: zgosalvez/github-actions-decrypt-secrets@v1
        with:
            secrets_file: .github/workflows/secrets/${{ steps.determine_environment.outputs.environment }}.json.gpg
            map: 'SECRET_PASSWORD=PASSWORD,PASSPHRASE=passphrase'
        env:
            GPG_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
      - name: Test (Do not expose your actual secrets!)
        run: |
          echo $SECRET_PASSWORD
          echo $PASSPHRASE