name: DockerFile Builder

on: [pull_request]

jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    name: Build Dockerfile and Run
    steps:
    - uses: actions/checkout@v2
    - id: DockerFileBuilder
      uses: enespekdas/composite-action-buildah@v1
      with:
        USERNAME: enespekdas
        PASSWORD: asdasd
        IMAGE_NAME: selam
        Repository_Project_Tag: action-test
        Repository_Project_version: latest
    - run: echo  ${{ steps.DockerFileBuilder.outputs.Result }} 
      shell: bash
    - run: echo " Selam , bitti"
      shell: bash
