name: DockerFile Builder

on: [push]

jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    name: Build Dockerfile and Run
    steps:
    - uses: actions/checkout@v2
    - id: DockerFileBuilder
      uses: enespekdas/github-composite-action-test@v2.2
      with:
        USERNAME: enespekdas
        PASSWORD: en.141220
        IMAGE_NAME: selam
        Repository_Project_Tag: action-test
        Repository_Project_version: latest
    - run: echo  ${{ steps.DockerFileBuilder.outputs.Result }} 
      shell: bash
    - run: echo " Selam , bitti"
      shell: bash