name: Buildah Example

on: [push]

jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    name: A job that copy files
    steps:
    - uses: actions/checkout@v2
    
    - run: sudo buildah bud -t selam .
      shell: bash
    - name : image kontrol
      run: sudo buildah images
      shell: bash
    - name : image push dockerhub
      run: sudo buildah push --creds ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWD }} selam:latest  ${{ secrets.DOCKER_USERNAME }}/action-test:latest
      shell: bash
    - name: pull image
      run: sudo buildah pull ${{ secrets.DOCKER_USERNAME }}/action-test:latest
      shell: bash
    - name: run image
      run: sudo  podman run -it ${{ secrets.DOCKER_USERNAME }}/docker-test:latest
      shell: bash
    - name: podman push
      run: sudo podman ps -a
      shell: bash
    - run: echo " Selam , bitti"
      shell: bash