sudo apt  install -y buildah

sudo apt install docker.io


FROM fedora:28
LABEL maintainer Emre Özkan <emreozkan@windowslive.com>

RUN dnf install -y tar gzip gcc make \
        && dnf clean all

ADD http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz /tmp/hello-2.10.tar.gz

RUN tar xvzf /tmp/hello-2.10.tar.gz -C /opt

WORKDIR /opt/hello-2.10

RUN ./configure
RUN make
RUN make install
RUN hello -v
ENTRYPOINT "/usr/local/bin/hello"


buildah bud -t hello . 

buildah images

buildah push --creds enespekdas:en.141220 hello:latest  enespekdas/docker-test:latest


buildah pull enespekdas/docker-test:latest

podman run -it enespekdas/docker-test:latest